version: '3'
services:
  web:
    build:
      context: angular
      dockerfile: Dockerfile
      target: build
    container_name: angular-app
    ports:
      - "4200:4200"
    volumes:
      - ./angular:/project
      - /project/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
